# 1. Credenciais da Base de Dados (O mapa para o Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/backend_respeito_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Comportamento do Hibernate / JPA (A Magia)
# 'update' diz ao Spring: "Se eu criar uma classe Java, cria a tabela no banco automaticamente"
spring.jpa.hibernate.ddl-auto=update
# Mostra no terminal o SQL real que o Spring está a gerar por baixo do capô
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true